inits <- function(chain){
  gen_list <- function(chain = chain){
    list(
      mu.omega = rnorm(1),
      tau.omega = rgamma(1,1,1),
      mu.mu.beta0 = rnorm(1),
      mu.tau.beta0 = rgamma(1,1,1),
      mu.mu.beta1 = rnorm(1),
      mu.tau.beta1 = rgamma(1,1,1),
      mu.mu.beta2 = rnorm(1),
      mu.tau.beta2 = rgamma(1,1,1),
      beta3 = rnorm(1),
      beta4 = rnorm(1),
      beta5 = rnorm(1),
      mu.mu.alpha0 = rnorm(1),
      mu.tau.alpha0 = rgamma(1,1,1),
      alpha1 = rnorm(1),
      alpha3 = rnorm(1),
      alpha4 = rnorm(1),
      mu.mu.alpha2 = rnorm(1),
      mu.tau.alpha2 = rgamma(1,1,1),
      mu.beta0 = rnorm(data_list$nOrder),
      mu.beta1 = rnorm(data_list$nOrder),
      mu.beta2 = rnorm(data_list$nOrder),
      mu.alpha0 = rnorm(data_list$nOrder),
      mu.alpha2 = rnorm(data_list$nOrder),
      tau.beta0 = rgamma(1,1,1),
      tau.beta1 = rgamma(1,1,1),
      tau.beta2 = rgamma(1,1,1),
      tau.alpha0 = rgamma(1,1,1),
      tau.alpha2 = rgamma(1,1,1),
      beta0 = matrix(1,
                     nrow = data_list$nTaxa,
                     ncol = data_list$nSite),
      beta1 = matrix(1,
                     nrow = data_list$nTaxa,
                     ncol = data_list$nSite),
      beta2 = matrix(1,
                     nrow = data_list$nTaxa,
                     ncol = data_list$nSite),
      omega = matrix(0.5,
                     nrow = data_list$nTaxa,
                     ncol = data_list$nSite),
      alpha0 = rnorm(data_list$nTaxa),
      alpha2 = rnorm(data_list$nTaxa),
      w = array(1, dim = c(max(data_list$nTaxa),
                           max(data_list$nSite))),
      N = array(1150, dim = c(data_list$nTaxa,
                              data_list$nSite,
                              data_list$nMonth)),
      .RNG.name = switch(chain,
                         "1" = "base::Wichmann-Hill",
                         "2" = "base::Marsaglia-Multicarry",
                         "3" = "base::Super-Duper",
                         "4" = "base::Mersenne-Twister",
                         "5" = "base::Wichmann-Hill",
                         "6" = "base::Marsaglia-Multicarry",
                         "7" = "base::Super-Duper",
                         "8" = "base::Mersenne-Twister"),
      .RNG.seed = sample(1:1e+06, 1)
    )
  }
  return(
    switch(
      chain,
      "1" = gen_list(chain),
      "2" = gen_list(chain),
      "3" = gen_list(chain),
      "4" = gen_list(chain),
      "5" = gen_list(chain),
      "6" = gen_list(chain),
      "7" = gen_list(chain),
      "8" = gen_list(chain)
    )
  )
}